// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: healthcheck/healthcheck/healthcheck_status.proto

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type HealthcheckStatus struct {
	Status              uint64 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Timestamp           uint64 `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Block               uint64 `protobuf:"varint,3,opt,name=block,proto3" json:"block,omitempty"`
	RegistryBlockHeight uint64 `protobuf:"varint,4,opt,name=registryBlockHeight,proto3" json:"registryBlockHeight,omitempty"`
}

func (m *HealthcheckStatus) Reset()         { *m = HealthcheckStatus{} }
func (m *HealthcheckStatus) String() string { return proto.CompactTextString(m) }
func (*HealthcheckStatus) ProtoMessage()    {}
func (*HealthcheckStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d23a5e61dc32eae, []int{0}
}
func (m *HealthcheckStatus) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *HealthcheckStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_HealthcheckStatus.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *HealthcheckStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthcheckStatus.Merge(m, src)
}
func (m *HealthcheckStatus) XXX_Size() int {
	return m.Size()
}
func (m *HealthcheckStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthcheckStatus.DiscardUnknown(m)
}

var xxx_messageInfo_HealthcheckStatus proto.InternalMessageInfo

func (m *HealthcheckStatus) GetStatus() uint64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *HealthcheckStatus) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *HealthcheckStatus) GetBlock() uint64 {
	if m != nil {
		return m.Block
	}
	return 0
}

func (m *HealthcheckStatus) GetRegistryBlockHeight() uint64 {
	if m != nil {
		return m.RegistryBlockHeight
	}
	return 0
}

func init() {
	proto.RegisterType((*HealthcheckStatus)(nil), "healthcheck.healthcheck.HealthcheckStatus")
}

func init() {
	proto.RegisterFile("healthcheck/healthcheck/healthcheck_status.proto", fileDescriptor_7d23a5e61dc32eae)
}

var fileDescriptor_7d23a5e61dc32eae = []byte{
	// 191 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x32, 0xc8, 0x48, 0x4d, 0xcc,
	0x29, 0xc9, 0x48, 0xce, 0x48, 0x4d, 0xce, 0xd6, 0xc7, 0xc1, 0x8e, 0x2f, 0x2e, 0x49, 0x2c, 0x29,
	0x2d, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0x47, 0x92, 0xd1, 0x43, 0x62, 0x2b, 0x4d,
	0x64, 0xe4, 0x12, 0xf4, 0x40, 0xf0, 0x83, 0xc1, 0x9a, 0x84, 0xc4, 0xb8, 0xd8, 0x20, 0xda, 0x25,
	0x18, 0x15, 0x18, 0x35, 0x58, 0x82, 0xa0, 0x3c, 0x21, 0x19, 0x2e, 0xce, 0x92, 0xcc, 0xdc, 0xd4,
	0xe2, 0x92, 0xc4, 0xdc, 0x02, 0x09, 0x26, 0xb0, 0x14, 0x42, 0x40, 0x48, 0x84, 0x8b, 0x35, 0x29,
	0x27, 0x3f, 0x39, 0x5b, 0x82, 0x19, 0x2c, 0x03, 0xe1, 0x08, 0x19, 0x70, 0x09, 0x17, 0xa5, 0xa6,
	0x67, 0x16, 0x97, 0x14, 0x55, 0x3a, 0x81, 0x04, 0x3c, 0x52, 0x33, 0xd3, 0x33, 0x4a, 0x24, 0x58,
	0xc0, 0x6a, 0xb0, 0x49, 0x39, 0x59, 0x9e, 0x78, 0x24, 0xc7, 0x78, 0xe1, 0x91, 0x1c, 0xe3, 0x83,
	0x47, 0x72, 0x8c, 0x13, 0x1e, 0xcb, 0x31, 0x5c, 0x78, 0x2c, 0xc7, 0x70, 0xe3, 0xb1, 0x1c, 0x43,
	0x94, 0x3c, 0xb2, 0x67, 0x2b, 0x50, 0xbc, 0x5e, 0x52, 0x59, 0x90, 0x5a, 0x9c, 0xc4, 0x06, 0xf6,
	0xae, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x2c, 0x57, 0xc5, 0xfc, 0x22, 0x01, 0x00, 0x00,
}

func (m *HealthcheckStatus) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *HealthcheckStatus) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *HealthcheckStatus) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.RegistryBlockHeight != 0 {
		i = encodeVarintHealthcheckStatus(dAtA, i, uint64(m.RegistryBlockHeight))
		i--
		dAtA[i] = 0x20
	}
	if m.Block != 0 {
		i = encodeVarintHealthcheckStatus(dAtA, i, uint64(m.Block))
		i--
		dAtA[i] = 0x18
	}
	if m.Timestamp != 0 {
		i = encodeVarintHealthcheckStatus(dAtA, i, uint64(m.Timestamp))
		i--
		dAtA[i] = 0x10
	}
	if m.Status != 0 {
		i = encodeVarintHealthcheckStatus(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintHealthcheckStatus(dAtA []byte, offset int, v uint64) int {
	offset -= sovHealthcheckStatus(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *HealthcheckStatus) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Status != 0 {
		n += 1 + sovHealthcheckStatus(uint64(m.Status))
	}
	if m.Timestamp != 0 {
		n += 1 + sovHealthcheckStatus(uint64(m.Timestamp))
	}
	if m.Block != 0 {
		n += 1 + sovHealthcheckStatus(uint64(m.Block))
	}
	if m.RegistryBlockHeight != 0 {
		n += 1 + sovHealthcheckStatus(uint64(m.RegistryBlockHeight))
	}
	return n
}

func sovHealthcheckStatus(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozHealthcheckStatus(x uint64) (n int) {
	return sovHealthcheckStatus(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *HealthcheckStatus) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowHealthcheckStatus
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: HealthcheckStatus: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: HealthcheckStatus: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHealthcheckStatus
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
			}
			m.Timestamp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHealthcheckStatus
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Timestamp |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Block", wireType)
			}
			m.Block = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHealthcheckStatus
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Block |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RegistryBlockHeight", wireType)
			}
			m.RegistryBlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHealthcheckStatus
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RegistryBlockHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipHealthcheckStatus(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthHealthcheckStatus
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipHealthcheckStatus(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowHealthcheckStatus
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowHealthcheckStatus
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowHealthcheckStatus
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthHealthcheckStatus
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupHealthcheckStatus
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthHealthcheckStatus
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthHealthcheckStatus        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowHealthcheckStatus          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupHealthcheckStatus = fmt.Errorf("proto: unexpected end of group")
)
